// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLoad.Data;

#nullable disable

namespace SmartLoad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250330070229_FixRouteNameConsistency")]
    partial class FixRouteNameConsistency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLoad.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LoadingSchemeId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PackagingTypeId")
                        .HasColumnType("integer");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RoutePointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoadingSchemeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PackagingTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RoutePointId");

                    b.ToTable("LoadingProducts");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoutId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoutId");

                    b.HasIndex("VehicleId");

                    b.ToTable("LoadingSchemes");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingSchemeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoadingSchemeId")
                        .HasColumnType("integer");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoadingSchemeId");

                    b.HasIndex("ProductId");

                    b.ToTable("LoadingSchemeItems");
                });

            modelBuilder.Entity("SmartLoad.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColProducts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistributorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoutePointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.HasIndex("RoutePointId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartLoad.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("SmartLoad.Models.PackagingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PackagingTypes");
                });

            modelBuilder.Entity("SmartLoad.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SmartLoad.Models.Rout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SmartLoad.Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UnloadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("SmartLoad.Models.RoutePointMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EstimatedArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderInRoute")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("RoutePointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("RoutePointId");

                    b.ToTable("RoutePointMappings");
                });

            modelBuilder.Entity("SmartLoad.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TractorAxleCount")
                        .HasColumnType("integer");

                    b.Property<float>("TractorEmptyFrontAxleLoad")
                        .HasColumnType("real");

                    b.Property<float>("TractorEmptyRearAxleLoad")
                        .HasColumnType("real");

                    b.Property<float>("TractorEmptyWeight")
                        .HasColumnType("real");

                    b.Property<string>("TractorFrontAxleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("TractorMaxFrontAxleLoad")
                        .HasColumnType("real");

                    b.Property<float>("TractorMaxLoadCapacity")
                        .HasColumnType("real");

                    b.Property<float>("TractorMaxRearAxleLoad")
                        .HasColumnType("real");

                    b.Property<string>("TractorModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("TractorRearAxleToKingpin")
                        .HasColumnType("real");

                    b.Property<string>("TractorRearAxleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("TractorWheelBase")
                        .HasColumnType("real");

                    b.Property<int>("TrailerAxleCount")
                        .HasColumnType("integer");

                    b.Property<float>("TrailerAxleSpread")
                        .HasColumnType("real");

                    b.Property<string>("TrailerAxleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("TrailerEmptyWeight")
                        .HasColumnType("real");

                    b.Property<float>("TrailerHeight")
                        .HasColumnType("real");

                    b.Property<float>("TrailerKingpinToAxle")
                        .HasColumnType("real");

                    b.Property<float>("TrailerLength")
                        .HasColumnType("real");

                    b.Property<float>("TrailerMaxAxleLoad")
                        .HasColumnType("real");

                    b.Property<float>("TrailerMaxLoadCapacity")
                        .HasColumnType("real");

                    b.Property<float>("TrailerMaxVolumeCapacity")
                        .HasColumnType("real");

                    b.Property<string>("TrailerModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("TrailerWidth")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingProduct", b =>
                {
                    b.HasOne("SmartLoad.Models.LoadingScheme", "LoadingScheme")
                        .WithMany("LoadingProducts")
                        .HasForeignKey("LoadingSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.Order", "Order")
                        .WithMany("LoadingProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.PackagingType", "PackagingType")
                        .WithMany()
                        .HasForeignKey("PackagingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.Product", "Product")
                        .WithMany("LoadingProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.RoutePoint", "RoutePoint")
                        .WithMany()
                        .HasForeignKey("RoutePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadingScheme");

                    b.Navigation("Order");

                    b.Navigation("PackagingType");

                    b.Navigation("Product");

                    b.Navigation("RoutePoint");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingScheme", b =>
                {
                    b.HasOne("SmartLoad.Models.Rout", "Rout")
                        .WithMany("LoadingSchemes")
                        .HasForeignKey("RoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.Vehicle", "Vehicle")
                        .WithMany("LoadingSchemes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rout");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingSchemeItem", b =>
                {
                    b.HasOne("SmartLoad.Models.LoadingScheme", "LoadingScheme")
                        .WithMany("LoadingSchemeItems")
                        .HasForeignKey("LoadingSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadingScheme");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartLoad.Models.Order", b =>
                {
                    b.HasOne("SmartLoad.Models.Distributor", "Distributor")
                        .WithMany("Orders")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.RoutePoint", "RoutePoint")
                        .WithMany("Orders")
                        .HasForeignKey("RoutePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("RoutePoint");
                });

            modelBuilder.Entity("SmartLoad.Models.OrderProduct", b =>
                {
                    b.HasOne("SmartLoad.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartLoad.Models.PackagingType", b =>
                {
                    b.HasOne("SmartLoad.Models.Product", "Product")
                        .WithMany("PackagingTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartLoad.Models.RoutePointMapping", b =>
                {
                    b.HasOne("SmartLoad.Models.Rout", "Route")
                        .WithMany("RoutePointMappings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLoad.Models.RoutePoint", "RoutePoint")
                        .WithMany("RoutePointMappings")
                        .HasForeignKey("RoutePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("RoutePoint");
                });

            modelBuilder.Entity("SmartLoad.Models.Distributor", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SmartLoad.Models.LoadingScheme", b =>
                {
                    b.Navigation("LoadingProducts");

                    b.Navigation("LoadingSchemeItems");
                });

            modelBuilder.Entity("SmartLoad.Models.Order", b =>
                {
                    b.Navigation("LoadingProducts");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("SmartLoad.Models.Product", b =>
                {
                    b.Navigation("LoadingProducts");

                    b.Navigation("PackagingTypes");
                });

            modelBuilder.Entity("SmartLoad.Models.Rout", b =>
                {
                    b.Navigation("LoadingSchemes");

                    b.Navigation("RoutePointMappings");
                });

            modelBuilder.Entity("SmartLoad.Models.RoutePoint", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RoutePointMappings");
                });

            modelBuilder.Entity("SmartLoad.Models.Vehicle", b =>
                {
                    b.Navigation("LoadingSchemes");
                });
#pragma warning restore 612, 618
        }
    }
}
